blank_issues_enabled: false # Prevents users from opening blank issues
contact_links:
  - name: GitHub Community Support
    url: https://github.com/Maakaf/maakaf_home/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Join our Discord channel
    url: https://discord.gg/uZvKfvG7NU
    about: For urgent questions or real-time discussions.